# Classifying

In [6]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [7]:
cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate', 'chocolate', 'strawberry', 'chocolate'),
    'Price', make_array(3.55, 4.75, 6.55, 5.25, 5.25)
)
cones

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 6.55
strawberry | 5.25
chocolate  | 5.25

In [3]:
# Default behavior is to count the number of 
# occurrences of each category
cones.group('Flavor')

Flavor     | count
chocolate  | 3
strawberry | 2

In [19]:
# Optionally, you can specify any function you want to see a different 
# characteristic of the categories.
# This computes the most expensive ice cream in each category
cones.group('Flavor', max)

Flavor     | Price max
chocolate  | 6.55
strawberry | 5.25

In [9]:
# This computes the average of all prices in the category
cones.group('Flavor', np.average)

Flavor     | Price average
chocolate  | 5.51667
strawberry | 4.4

In [8]:
nba = Table.read_table('nba_salaries.csv')
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

# Practice 1
Find the total amount of money each team paid out in salaries.
(Start by selecting only the columns you need.)

# Practice 2
Find the average salary earned by players in each position. (Start by selecting only the columns you need.)

# Classifying by multiple variables

In [4]:
more_cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate', 'chocolate', 'strawberry', 'chocolate', 'bubblegum'),
    'Color', make_array('pink', 'light brown', 'dark brown', 'pink', 'dark brown', 'pink'),
    'Price', make_array(3.55, 4.75, 5.25, 5.25, 5.25, 4.75)
)

more_cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [5]:
# Can provide a list of multiple categories to group by
more_cones.group(['Flavor', 'Color'])

Flavor     | Color       | count
bubblegum  | pink        | 1
chocolate  | dark brown  | 2
chocolate  | light brown | 1
strawberry | pink        | 2

In [6]:
# Just like with a single variable, you can provide 
# a function to look at a different characteristic
more_cones.group(['Flavor', 'Color'], max)

Flavor     | Color       | Price max
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
strawberry | pink        | 5.25

# Practice 3
Find the total paid in salaries by each team *during each season*. (Start by selecting only the columns you need.)

In [13]:
team_salaries = nba.select('team', 'salary')
team_salaries = team_salaries.group('team', sum)
team_salaries

team                        | salary sum
Atlanta Hawks               | 1146345077
Bilbao Basket Bilbao Basket | 5543116
Boston Celtics              | 1353465387
Brooklyn Nets               | 791940722
Charlotte Bobcats           | 546931673
Charlotte Hornets           | 726794747
Chicago Bulls               | 1199006636
Cleveland Cavaliers         | 1341890490
Dallas Mavericks            | 1395522485
Denver Nuggets              | 1277692469
... (33 rows omitted)